services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    container_name: php_mvc_app
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "3030:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password


